# Generated by Django 4.2 on 2023-10-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('max_hourly_energy_consumption', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
    ]
